from __future__ import annotations

import json
from pathlib import Path

from .models import RepositoryModel


def write_outputs(model: RepositoryModel, root: Path) -> list[Path]:
    state = root / ".reposchematic"
    state.mkdir(exist_ok=True)
    repo_json = state / "repo.json"
    graph_json = state / "graph.json"
    repo_json.write_text(json.dumps(model.to_dict(), indent=2, sort_keys=True), encoding="utf-8")
    graph_json.write_text(json.dumps({"edges": [e.__dict__ if hasattr(e, '__dict__') else _edge_dict(e) for e in model.edges]}, indent=2), encoding="utf-8")
    paths = [repo_json, graph_json]
    for name, text in [
        ("REPO_MAP.md", render_repo_map(model)),
        ("ARCHITECTURE.md", render_architecture(model)),
        ("AI_CONTEXT.md", render_ai_context(model)),
    ]:
        p = root / name
        p.write_text(text, encoding="utf-8")
        paths.append(p)
    return paths


def _edge_dict(edge):
    return {
        "source": edge.source, "target": edge.target, "relation": edge.relation,
        "evidence": None if edge.evidence is None else {
            "kind": edge.evidence.kind, "detail": edge.evidence.detail,
            "path": edge.evidence.path, "line": edge.evidence.line,
        },
    }


def render_repo_map(model: RepositoryModel) -> str:
    top = model.ranked_files[:15]
    langs = ", ".join(f"{k} ({v})" for k, v in model.stats.get("languages", {}).items()) or "n/a"
    lines = [
        f"# Repository Map: {model.name}", "",
        "> Generated by RepoSchematic from repository structure and static analysis. No cloud model was used.", "",
        "## Snapshot", "",
        f"- Files analyzed: **{model.stats['files']}**",
        f"- Internal dependency edges: **{model.stats['edges']}**",
        f"- Symbols detected: **{model.stats['symbols']}**",
        f"- Languages: {langs}",
        f"- Tech stack: {', '.join(model.tech_stack) if model.tech_stack else 'Not confidently detected'}", "",
        "## Where to start", "",
    ]
    if top:
        for item in top[:8]:
            reason = "; ".join(item.reasons) or "structural relevance"
            lines.append(f"- **`{item.path}`** — {item.level} ({item.score:g}): {reason}")
    else:
        lines.append("- No analyzable files were found.")
    lines += ["", "## Entry points", ""]
    if model.entry_points:
        for e in model.entry_points:
            ev = e.evidence[0].detail if e.evidence else "heuristic"
            cmd = f" — `{e.command}`" if e.command else ""
            lines.append(f"- **`{e.path}`** ({e.confidence} confidence){cmd}. Evidence: {ev}")
    else:
        lines.append("- No entry point was detected with sufficient confidence.")
    lines += ["", "## Important files", "", "| File | Importance | Score | Evidence |", "|---|---:|---:|---|"]
    for item in top:
        lines.append(f"| `{item.path}` | {item.level} | {item.score:g} | {'; '.join(item.reasons) or '—'} |")
    lines += ["", "## Warnings", ""]
    if model.warnings:
        lines.extend(f"- {w}" for w in model.warnings)
    else:
        lines.append("- None.")
    lines += ["", "---", "RepoSchematic reports evidence-backed structure; treat medium-confidence heuristics as navigation hints, not ground truth.", ""]
    return "\n".join(lines)


def render_architecture(model: RepositoryModel) -> str:
    categories = {f.path: f.category for f in model.files}
    source_edges = [
        e for e in model.edges
        if categories.get(e.source) != "test" and categories.get(e.target) != "test"
        and not e.source.startswith("tests/fixtures/") and not e.target.startswith("tests/fixtures/")
    ]
    edges = source_edges[:60]
    lines = [f"# Architecture: {model.name}", "", "## Internal dependency map", "",
             "> The primary graph focuses on production/configuration code; test edges are omitted for readability.", ""]
    if edges:
        lines += ["```mermaid", "flowchart LR"]
        ids: dict[str, str] = {}
        def node_id(path: str) -> str:
            if path not in ids:
                ids[path] = f"N{len(ids)+1}"
            return ids[path]
        for edge in edges:
            a, b = node_id(edge.source), node_id(edge.target)
            lines.append(f'    {a}["{edge.source}"] --> {b}["{edge.target}"]')
        lines.append("```")
    else:
        lines.append("No internal import graph was detected.")
    lines += ["", "## Entry-point evidence", ""]
    for e in model.entry_points:
        lines.append(f"### `{e.path}` — {e.confidence} confidence")
        if e.command:
            lines.append(f"Command: `{e.command}`")
        for ev in e.evidence:
            where = f" ({ev.path}:{ev.line})" if ev.path and ev.line else f" ({ev.path})" if ev.path else ""
            lines.append(f"- {ev.kind}: {ev.detail}{where}")
        lines.append("")
    js_modes = {f.parse_status for f in model.files if f.language in {"JavaScript", "TypeScript"}}
    js_line = "- JavaScript/TypeScript used Tree-sitter AST analysis." if "ok-tree-sitter" in js_modes else "- JavaScript/TypeScript used the conservative dependency-free fallback; install `reposchematic[treesitter]` for AST-backed parsing."
    lines += ["## Analysis boundaries", "", "- Python structure is parsed with the standard-library AST.", js_line, "- Dynamic imports, runtime dependency injection, reflection, generated code, and framework magic may not appear in the graph.", ""]
    return "\n".join(lines)


def render_ai_context(model: RepositoryModel) -> str:
    top = model.ranked_files[:12]
    lines = [
        f"# AI Context: {model.name}", "",
        "> Compact repository context generated deterministically by RepoSchematic.", "",
        "## Repository facts", "",
        f"- Files analyzed: {model.stats['files']}",
        f"- Internal dependency edges: {model.stats['edges']}",
        f"- Tech stack: {', '.join(model.tech_stack) if model.tech_stack else 'not confidently detected'}", "",
        "## Entry points", "",
    ]
    if model.entry_points:
        for e in model.entry_points:
            lines.append(f"- `{e.path}` — {e.kind}, {e.confidence} confidence" + (f", command `{e.command}`" if e.command else ""))
    else:
        lines.append("- None confidently detected.")
    lines += ["", "## Read these files first", ""]
    for item in top:
        lines.append(f"- `{item.path}` — {item.level}; {'; '.join(item.reasons) or 'structural relevance'}")
    lines += ["", "## Safe modification guidance", "", "- Check reverse dependencies before changing a high-importance module.", "- Run the repository's existing test suite after edits.", "- Do not treat generated RepoSchematic documents as source-of-truth over the code itself.", "- Secret-like files and common credential paths are intentionally excluded from analysis.", ""]
    return "\n".join(lines)
